name: Velodrome V3 Indexer
contracts:
  - name: CLFactory
    abi_file_path: src/abis/factoryAbi.json
    handler: src/EventHandlerFactory.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, int24 indexed tickSpacing, address pool)
        isAsync: true
  - name: CLPool
    abi_file_path: src/abis/poolAbi.json
    handler: src/EventHandlerPools.ts
    events:
      - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        isAsync: true
      - event: Collect(address indexed owner, address recipient, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount0, uint128 amount1)
        isAsync: true
      - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        isAsync: true
      - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
        isAsync: true
networks:
  - id: 8453
    start_block: 13843700
    contracts:
      - name: CLFactory
        address:
          - 0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A
      - name: CLPool
        address:
event_decoder: viem
